# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
executors:
  main-env:
    docker:
      - image: firesim/firesim-ci:wip-git
        user: "centos"
    environment:
        JVM_MEMORY: 2200m # Customize the JVM maximum heap limit
        LANG: en_US.UTF-8 # required by sbt when it sees boost directories

commands:
  machinelaunchscript:
    description: "Run firesim's machine launch script"
    steps:
      - run:
          command: |
            cd scripts && /usr/bin/bash ./machine-launch-script.sh

  buildsetup:
    description: "Run firesim's build-setup.sh"
    steps:
      - run:
          command: |
            ./build-setup.sh fast

  scala-build:
    description: "Compile all relevant Scala sources for CI"
    steps:
      - run:
          command: |
            source env.sh
            make -C sim TARGET_PROJECT=firesim sbt SBT_COMMAND=test:compile

  cache-repo:
    description: "Caches a enormous snapshot of the FireSim repo."
    steps:
      - run:
          command: |
            # This interacts badly with running machine launch on the instance
            # we are restoring the cache
            rm -rf scripts/verilator
      - save_cache:
          key: repo-{{ .Revision }}
          paths:
            - "."

  firesimtest-manual-midasexamples:
    description: "Run a test"
    steps:
      - restore_cache:
          keys:
          - repo-{{ .Revision }}
      - run:
          command: |
            source env.sh
            make -C sim run-verilator LOGFILE= WAVEFORM= ARGS=+tracelen=8 TARGET_PROJECT=midasexamples DESIGN=Stack TARGET_CONFIG=NoConfig PLATFORM_CONFIG=HostDebugFeatures_DefaultF1Config PLATFORM=f1

  build-scala-doc:
    description: "Compiles Scala Doc"
    steps:
      - restore_cache:
          keys:
          - repo-{{ .Revision }}
      - run:
          command: |
            source env.sh
            make -C sim scaladoc

jobs:
  repo-setup:
    executor: main-env
    steps:
      - checkout
      - machinelaunchscript
      - buildsetup
      - scala-build
      - cache-repo

  run-scala-test:
    executor: main-env
    steps:
      - restore_cache:
          keys:
          - repo-{{ .Revision }}
      - machinelaunchscript
      - firesimtest-manual-midasexamples

  build-scala-doc:
    executor: main-env
    steps:
      - restore_cache:
          keys:
          - repo-{{ .Revision }}
      - machinelaunchscript
      - build-scala-doc

workflows:
   version: 2

   firesimCIall:
     jobs:
       - repo-setup

       - run-scala-test:
           requires:
             - repo-setup

       - build-scala-doc:
           requires:
             - repo-setup
