# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
executors:
  main-env:
    docker:
      - image: firesim/firesim-ci:wip-git
        user: "centos"
    environment:
        JVM_MEMORY: 3200m # Customize the JVM maximum heap limit
        LANG: en_US.UTF-8 # required by sbt when it sees boost directories

commands:
  machinelaunchscript:
    description: "Run firesim's machine launch script"
    steps:
      - run:
          command: |
            cd scripts && /usr/bin/bash ./machine-launch-script.sh

  buildsetup:
    description: "Run firesim's build-setup.sh"
    steps:
      - run:
          command: |
            ./build-setup.sh fast

  scala-build:
    description: "Compile all relevant Scala sources for CI"
    steps:
      - run:
          command: |
            source env.sh
            make -C sim TARGET_PROJECT=firesim sbt SBT_COMMAND=test:compile

  firesimtest-manual-midasexamples:
    description: "Run a test"
    steps:
      - run:
          command: |
            source env.sh
            make -C sim run-verilator LOGFILE= WAVEFORM= ARGS=+tracelen=8 TARGET_PROJECT=midasexamples DESIGN=Stack TARGET_CONFIG=NoConfig PLATFORM_CONFIG=HostDebugFeatures_DefaultF1Config PLATFORM=f1

  build-scala-doc:
    description: "Compiles Scala Doc"
    steps:
      - run:
          command: |
            source env.sh
            make -C sim scaladoc

  push-scaladoc-to-ghpages:
    description: "Pushes scaladoc to ghphage branch"
    steps:
      - run:
          command: |
            source env.sh
            make -C sim TARGET_PROJECT=firesim sbt SBT_COMMAND=ghpagesPushSite

  repo-setup:
    description: "Runs all baseline setup tasks up to scala compilation."
    steps:
      - checkout
      - machinelaunchscript
      - buildsetup
      - scala-build

jobs:
  run-tests:
    executor: main-env
    steps:
      - repo-setup
      - firesimtest-manual-midasexamples
      - build-scala-doc

  publish-scala-doc:
    executor: main-env
    steps:
      - repo-setup
      - build-scala-doc
      - push-scaladoc-to-ghpages

workflows:
   version: 2

   firesimCIall:
     jobs:
       - run-tests

       - publish-scala-doc:
           filters:
             branches:
               only:
                 - dev
                 - scala-doc-ci-builds

